services:
  haproxy:
    build: .
    container_name: haproxy

    ports:
      - "443:443"

    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./cloudflare_ips.txt:/etc/haproxy/cloudflare_ips.txt:ro

    networks:
      - shared

networks:
  shared:
    external: true
    name: shared_network
